package com.atguigu.dao;

import com.atguigu.pojo.TravelGroup;
import com.github.pagehelper.Page;

import java.util.List;
import java.util.Map;

public interface TravelGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_travelgroup
     *
     * @mbg.generated Thu Jun 17 17:20:34 SGT 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_travelgroup
     *
     * @mbg.generated Thu Jun 17 17:20:34 SGT 2021
     */
    int insert(TravelGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_travelgroup
     *
     * @mbg.generated Thu Jun 17 17:20:34 SGT 2021
     */
    TravelGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_travelgroup
     *
     * @mbg.generated Thu Jun 17 17:20:34 SGT 2021
     * @param queryString
     */
    Page selectAll(String queryString);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_travelgroup
     *
     * @mbg.generated Thu Jun 17 17:20:34 SGT 2021
     */
    int updateByPrimaryKey(TravelGroup record);

    void setTravelGroupAndTravelItem(Map<String, Integer> map);

    List<Integer> findGroupAndItemByGroupId(Integer id);

    void deleteTravelGroupAndItemByTravelItemId(Integer id);
}