package com.atguigu.dao;

import com.atguigu.pojo.TravelGroup;
import java.util.List;

public interface TravelGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_travelgroup
     *
     * @mbg.generated Thu Jun 17 17:20:34 SGT 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_travelgroup
     *
     * @mbg.generated Thu Jun 17 17:20:34 SGT 2021
     */
    int insert(TravelGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_travelgroup
     *
     * @mbg.generated Thu Jun 17 17:20:34 SGT 2021
     */
    TravelGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_travelgroup
     *
     * @mbg.generated Thu Jun 17 17:20:34 SGT 2021
     */
    List<TravelGroup> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_travelgroup
     *
     * @mbg.generated Thu Jun 17 17:20:34 SGT 2021
     */
    int updateByPrimaryKey(TravelGroup record);
}