package com.atguigu.dao;

import com.atguigu.pojo.TravelItem;
import com.github.pagehelper.Page;

import java.util.List;

public interface TravelItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_travelitem
     *
     * @mbg.generated Thu Jun 17 17:20:34 SGT 2021
     */
    int deleteByPrimaryKey(Integer id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_travelitem
     *
     * @mbg.generated Thu Jun 17 17:20:34 SGT 2021
     */
    int insert(TravelItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_travelitem
     *
     * @mbg.generated Thu Jun 17 17:20:34 SGT 2021
     */
    TravelItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_travelitem
     *
     * @mbg.generated Thu Jun 17 17:20:34 SGT 2021
     */
    Page<TravelItem> selectAll(String queryString);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_travelitem
     *
     * @mbg.generated Thu Jun 17 17:20:34 SGT 2021
     */
    int updateByPrimaryKey(TravelItem record);
}